# This is a global WikiWire configuration file, a CI action which automatically syncs and uploads modules and templates from a Git repo towards a production or upstream MediaWiki instance via bot passwords and the MediaWiki Action API.
# Learn more: https://github.com/obbywiki/wikiwire

version = 1
shared = true

[[sites]]
id = "utg"
site = "utg.miraheze.org"
api = "https://utg.miraheze.org/w/api.php"

[[sites]]
id = "ufg"
site = "farm.miraheze.org"
api = "https://farm.miraheze.org/w/api.php"